using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Namaa.Domain.ReferenceData;

namespace Namaa.Infrastructure.Persistence.Configurations;
public class CropConfiguration : IEntityTypeConfiguration<Crop>
{
    public void Configure(EntityTypeBuilder<Crop> builder)
    {
        builder.ToTable("Crops");
        builder.HasKey(c => c.Id);

        builder.HasOne(c => c.Governorate)
            .WithMany() 
            .HasForeignKey(c => c.GovernorateId)
            .OnDelete(DeleteBehavior.Restrict); 
            
        builder.Property(c => c.ImageUrl).HasMaxLength(500); 
        builder.Property(c => c.DaysToHarvest).IsRequired();

        builder.Property(c => c.Name).HasMaxLength(100).IsRequired();
        builder.Property(c => c.Category).HasMaxLength(50);
        builder.Property(c => c.Season).HasMaxLength(50);
        builder.Property(c => c.FarmingMethod).HasMaxLength(100);
        builder.Property(c => c.PlantingTime).HasMaxLength(50);
        builder.Property(c => c.HarvestTime).HasMaxLength(50);

        builder.Property(c => c.MinTemperature).IsRequired();
        builder.Property(c => c.MaxTemperature).IsRequired();

        builder.Property(c => c.IrrigationLevel).HasMaxLength(50);
        builder.Property(c => c.WaterRequirementCategory).HasMaxLength(50);

        // 💰 UPGRADED: SQL constraints for Decimal Money values
        builder.Property(c => c.MinExpectedPrice).HasColumnType("decimal(18,2)");
        builder.Property(c => c.MaxExpectedPrice).HasColumnType("decimal(18,2)");
        builder.Property(c => c.MinEstimatedCost).HasColumnType("decimal(18,2)");
        builder.Property(c => c.MaxEstimatedCost).HasColumnType("decimal(18,2)");

        builder.HasData(
            new Crop(
                id: 1,
                governorateId: 11,
                name: "Tomato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "25/8–10/9",
                harvestTime: "1/11–1/4",
                minTemperature: 20,
                maxTemperature: 25,
                irrigationLevel: "120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 18.0,
                maxProductionPerDonum: 20.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 5000m,
                maxEstimatedCost: 6000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 65
            ),
            new Crop(
                id: 2,
                governorateId: 11,
                name: "Cucumber",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "1/9–15/10",
                harvestTime: "1/12–30/3",
                minTemperature: 18,
                maxTemperature: 25,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 10.0,
                maxProductionPerDonum: 12.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 5.0m,
                minEstimatedCost: 3500m,
                maxEstimatedCost: 5000m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 3,
                governorateId: 11,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "15/9–15/10",
                harvestTime: "1/12–30/4",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "110–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 12.0m,
                minEstimatedCost: 3500m,
                maxEstimatedCost: 4500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 4,
                governorateId: 11,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Sandy Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 5,
                governorateId: 11,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "110–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 8.0,
                maxProductionPerDonum: 10.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 6,
                governorateId: 11,
                name: "Watermelon",
                category: "Fruits",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/2–1/3",
                harvestTime: "1/5–15/6",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 1500m,
                maxEstimatedCost: 2500m,
                imageUrl: "https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 7,
                governorateId: 11,
                name: "Melon",
                category: "Fruits",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/2-1/3",
                harvestTime: "1/5-15/6",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "80-100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 3.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 2000m,
                imageUrl: "https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 8,
                governorateId: 11,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6–30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 9,
                governorateId: 7,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 10,
                governorateId: 7,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–140",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 11,
                governorateId: 7,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 80
            ),
            new Crop(
                id: 12,
                governorateId: 7,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 13,
                governorateId: 7,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 14,
                governorateId: 7,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Rendzina Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 15,
                governorateId: 7,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 16,
                governorateId: 7,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6-30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60-80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 17,
                governorateId: 8,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "80–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 18,
                governorateId: 8,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 5.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 19,
                governorateId: 8,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 80
            ),
            new Crop(
                id: 20,
                governorateId: 8,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 21,
                governorateId: 8,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 22,
                governorateId: 8,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 23,
                governorateId: 8,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 24,
                governorateId: 8,
                name: "Green Beans",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "1/3–1/4",
                harvestTime: "1/5–30/6",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "70–90",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 1.5,
                maxProductionPerDonum: 2.5,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 1000m,
                maxEstimatedCost: 1500m,
                imageUrl: "https://images.unsplash.com/photo-1533116584281-222a104031df?w=500",
                daysToHarvest: 55
            ),
            new Crop(
                id: 25,
                governorateId: 6,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.4,
                maxProductionPerDonum: 0.6,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 26,
                governorateId: 6,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Red Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 27,
                governorateId: 6,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–140",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 28,
                governorateId: 6,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 29,
                governorateId: 6,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 30,
                governorateId: 6,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Clay Soil", "Sandy Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 31,
                governorateId: 6,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 32,
                governorateId: 6,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6–30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Clay Soil", "Red Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 33,
                governorateId: 5,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.4,
                maxProductionPerDonum: 0.6,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 34,
                governorateId: 5,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 35,
                governorateId: 5,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 36,
                governorateId: 5,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 37,
                governorateId: 5,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 38,
                governorateId: 5,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 39,
                governorateId: 5,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 40,
                governorateId: 5,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6–30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 41,
                governorateId: 2,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 42,
                governorateId: 2,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 3.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 43,
                governorateId: 2,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 44,
                governorateId: 2,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 45,
                governorateId: 2,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 46,
                governorateId: 2,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 47,
                governorateId: 2,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 48,
                governorateId: 2,
                name: "Green Beans",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "1/3–1/4",
                harvestTime: "1/5–30/6",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "70–90",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 1.5,
                maxProductionPerDonum: 2.5,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 1000m,
                maxEstimatedCost: 1500m,
                imageUrl: "https://images.unsplash.com/photo-1533116584281-222a104031df?w=500",
                daysToHarvest: 55
            ),
            new Crop(
                id: 49,
                governorateId: 1,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 50,
                governorateId: 1,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 51,
                governorateId: 1,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 52,
                governorateId: 1,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 53,
                governorateId: 1,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 54,
                governorateId: 1,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 55,
                governorateId: 1,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 56,
                governorateId: 1,
                name: "Peas",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/11–15/12",
                harvestTime: "1/3–30/4",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "40–60",
                waterRequirementCategory: "Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 1.0,
                maxProductionPerDonum: 2.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 8.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 57,
                governorateId: 3,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 58,
                governorateId: 3,
                name: "Barley",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 1.5m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 400m,
                maxEstimatedCost: 800m,
                imageUrl: "https://images.unsplash.com/photo-1533758313437-080353c7a6e1?w=500",
                daysToHarvest: 180
            ),
            new Crop(
                id: 59,
                governorateId: 3,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 3.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 60,
                governorateId: 3,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 61,
                governorateId: 3,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 62,
                governorateId: 3,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 63,
                governorateId: 3,
                name: "Peas",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/11–15/12",
                harvestTime: "1/3–30/4",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "40–60",
                waterRequirementCategory: "Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 1.0,
                maxProductionPerDonum: 2.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 8.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 64,
                governorateId: 3,
                name: "Lentils",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.2,
                maxProductionPerDonum: 0.4,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 400m,
                maxEstimatedCost: 700m,
                imageUrl: "https://images.unsplash.com/photo-1515942661900-94b3d197c591?w=500",
                daysToHarvest: 160
            ),
            new Crop(
                id: 65,
                governorateId: 4,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 66,
                governorateId: 4,
                name: "Barley",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.3,
                maxProductionPerDonum: 0.5,
                minExpectedPrice: 1.5m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 400m,
                maxEstimatedCost: 800m,
                imageUrl: "https://images.unsplash.com/photo-1533758313437-080353c7a6e1?w=500",
                daysToHarvest: 180
            ),
            new Crop(
                id: 67,
                governorateId: 4,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "70–90",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 3.0,
                maxProductionPerDonum: 4.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 68,
                governorateId: 4,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–70",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 69,
                governorateId: 4,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 70,
                governorateId: 4,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 71,
                governorateId: 4,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "80–100",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 72,
                governorateId: 4,
                name: "Peas",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/11–15/12",
                harvestTime: "1/3–30/4",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "40–60",
                waterRequirementCategory: "Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 1.0,
                maxProductionPerDonum: 2.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 8.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 73,
                governorateId: 9,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.4,
                maxProductionPerDonum: 0.6,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 74,
                governorateId: 9,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 3.0,
                maxProductionPerDonum: 5.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 75,
                governorateId: 9,
                name: "Lettuce",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "1/10–20/10",
                harvestTime: "15/12–31/1",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "50–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 600m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 76,
                governorateId: 9,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 77,
                governorateId: 9,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 78,
                governorateId: 9,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 79,
                governorateId: 9,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 80,
                governorateId: 9,
                name: "Green Beans",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "1/3–1/4",
                harvestTime: "1/5–30/6",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "70–90",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 1.5,
                maxProductionPerDonum: 2.5,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 1000m,
                maxEstimatedCost: 1500m,
                imageUrl: "https://images.unsplash.com/photo-1533116584281-222a104031df?w=500",
                daysToHarvest: 55
            ),
            new Crop(
                id: 81,
                governorateId: 10,
                name: "Wheat",
                category: "Field Crops",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/11–30/12",
                harvestTime: "1/5–30/6",
                minTemperature: 10,
                maxTemperature: 20,
                irrigationLevel: "0–10",
                waterRequirementCategory: "Very Low",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 0.4,
                maxProductionPerDonum: 0.6,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 2.0m,
                minEstimatedCost: 500m,
                maxEstimatedCost: 900m,
                imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500",
                daysToHarvest: 190
            ),
            new Crop(
                id: 82,
                governorateId: 10,
                name: "Potato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Red Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 83,
                governorateId: 10,
                name: "Tomato",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/6–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–140",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 2000m,
                maxEstimatedCost: 3000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 95
            ),
            new Crop(
                id: 84,
                governorateId: 10,
                name: "Cucumber",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/3–15/4",
                harvestTime: "1/5–30/7",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 85,
                governorateId: 10,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Summer",
                farmingMethod: "Greenhouse",
                plantingTime: "15/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 20,
                maxTemperature: 30,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 85
            ),
            new Crop(
                id: 86,
                governorateId: 10,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 50
            ),
            new Crop(
                id: 87,
                governorateId: 10,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 110
            ),
            new Crop(
                id: 88,
                governorateId: 10,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6–30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Red Soil", "Clay Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 89,
                governorateId: 12,
                name: "Tomato",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "1/9–15/10",
                harvestTime: "1/12–30/3",
                minTemperature: 18,
                maxTemperature: 25,
                irrigationLevel: "120–150",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 15.0,
                maxProductionPerDonum: 22.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 5.0m,
                minEstimatedCost: 5000m,
                maxEstimatedCost: 6000m,
                imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 90,
                governorateId: 12,
                name: "Cucumber",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "1/9–15/10",
                harvestTime: "1/12–30/3",
                minTemperature: 18,
                maxTemperature: 25,
                irrigationLevel: "90–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 8.0,
                maxProductionPerDonum: 12.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 5.0m,
                minEstimatedCost: 3500m,
                maxEstimatedCost: 5000m,
                imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 91,
                governorateId: 12,
                name: "Sweet Pepper",
                category: "Vegetables",
                season: "Winter",
                farmingMethod: "Greenhouse",
                plantingTime: "15/9–15/10",
                harvestTime: "1/12–30/4",
                minTemperature: 20,
                maxTemperature: 28,
                irrigationLevel: "100–130",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 6.0,
                maxProductionPerDonum: 8.0,
                minExpectedPrice: 6.0m,
                maxExpectedPrice: 10.0m,
                minEstimatedCost: 3000m,
                maxEstimatedCost: 4000m,
                imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa8a?w=500",
                daysToHarvest: 75
            ),
            new Crop(
                id: 92,
                governorateId: 12,
                name: "Potato",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/10–30/11",
                harvestTime: "15/2–30/4",
                minTemperature: 15,
                maxTemperature: 22,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 3.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500",
                daysToHarvest: 120
            ),
            new Crop(
                id: 93,
                governorateId: 12,
                name: "Eggplant",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Greenhouse",
                plantingTime: "1/2–15/3",
                harvestTime: "15/5–30/8",
                minTemperature: 22,
                maxTemperature: 30,
                irrigationLevel: "100–120",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil", "Clay Soil" },
                minProductionPerDonum: 7.0,
                maxProductionPerDonum: 9.0,
                minExpectedPrice: 3.0m,
                maxExpectedPrice: 6.0m,
                minEstimatedCost: 2500m,
                maxEstimatedCost: 3500m,
                imageUrl: "https://images.unsplash.com/photo-1629856169935-7c9808381ddf?w=500",
                daysToHarvest: 100
            ),
            new Crop(
                id: 94,
                governorateId: 12,
                name: "Zucchini",
                category: "Vegetables",
                season: "Spring",
                farmingMethod: "Open Field",
                plantingTime: "15/2–15/3",
                harvestTime: "15/4–30/6",
                minTemperature: 18,
                maxTemperature: 28,
                irrigationLevel: "90–110",
                waterRequirementCategory: "High",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 5.0,
                maxProductionPerDonum: 7.0,
                minExpectedPrice: 4.0m,
                maxExpectedPrice: 7.0m,
                minEstimatedCost: 1200m,
                maxEstimatedCost: 1800m,
                imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=500",
                daysToHarvest: 60
            ),
            new Crop(
                id: 95,
                governorateId: 12,
                name: "Watermelon",
                category: "Fruits",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "1/2–1/3",
                harvestTime: "1/5–15/6",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "80–100",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 4.0,
                maxProductionPerDonum: 6.0,
                minExpectedPrice: 2.0m,
                maxExpectedPrice: 4.0m,
                minEstimatedCost: 1500m,
                maxEstimatedCost: 2500m,
                imageUrl: "https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=500",
                daysToHarvest: 90
            ),
            new Crop(
                id: 96,
                governorateId: 12,
                name: "Molokhia",
                category: "Leafy Greens",
                season: "Summer",
                farmingMethod: "Open Field",
                plantingTime: "15/3–30/4",
                harvestTime: "1/6–30/8",
                minTemperature: 25,
                maxTemperature: 35,
                irrigationLevel: "60–80",
                waterRequirementCategory: "Medium",
                suitableSoilTypes: new List<string> { "Sandy Soil" },
                minProductionPerDonum: 2.0,
                maxProductionPerDonum: 3.0,
                minExpectedPrice: 5.0m,
                maxExpectedPrice: 9.0m,
                minEstimatedCost: 800m,
                maxEstimatedCost: 1200m,
                imageUrl: "https://images.unsplash.com/photo-1625944227393-276182bf544e?w=500",
                daysToHarvest: 75
            )
        );

    }
}