@baseURL=https://localhost:7070
###
Post {{baseURL}}/api/controller/login
Content-Type: application/json

{
"Email":"test@namaa.com",
"Password":"Pass1234!" 
}
###
GET {{baseURL}}/api/controller/trusted
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTBjNDEyYy0yMmZiLTQ5MTMtYjY5ZS0wOGRlNjRiOTE5ZGUiLCJlbWFpbCI6InRlc3RAbmFtYWEuY29tIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NzAzMTAzOTIsImV4cCI6MTc3MDMxMzk5MiwiaWF0IjoxNzcwMzEwMzkyLCJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJsb2NhbGhvc3QifQ.gDb52SQTp3i3SExcsWs6WJVaCMymMkinoqXM2e1zrSA