using Namaa.Api;
using Namaa.Infrastructure;
using Namaa.Infrastructure.Seeder;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddAppConfiguration();
builder.Services.AddInfrastructure(builder.Configuration);
var app = builder.Build();
app.UseCoreMiddlewares(builder.Configuration);
app.MapControllers();
app.Run();
